# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Silly Slots' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_modular_headers!

  # Pods for Silly Slots
	pod 'AlamofireImage'
	pod 'Parse'
	pod 'BigInt', '~> 5.2'
	pod 'web3swift'

end
